"""ptransfer - phone data transfer and rescue toolkit.

Core library is dependency-free so it can be used from the CLI, the GUI or
from tests without installing anything beyond the standard library.
"""

from __future__ import annotations

import os

# Base version. The Windows build overwrites this with a unique, increasing
# build number (see ._build, written by CI) so no two downloads ever clash.
_BASE_VERSION = "0.1.0"


def _resolve_version() -> str:
    override = os.environ.get("PTRANSFER_VERSION")
    if override:
        return override
    try:
        from ._build import VERSION  # generated by the build, absent in the repo

        if VERSION:
            return VERSION
    except Exception:
        pass
    return _BASE_VERSION


__version__ = _resolve_version()

BUNDLE_SCHEMA_VERSION = 1
BUNDLE_SUFFIX = ".ptbundle"
